<?php

namespace AppBundle\Repository;

/**
 * EstadoRioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRioRepository extends \Doctrine\ORM\EntityRepository
{
}
