<?php

namespace AppBundle\Repository;

/**
 * PuertoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuertoRepository extends \Doctrine\ORM\EntityRepository
{
}
