<?php

namespace AppBundle\Repository;

/**
 * RioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RioRepository extends \Doctrine\ORM\EntityRepository
{
}
