<?php

namespace AppBundle\Repository;

/**
 * SubscriptorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriptorRepository extends \Doctrine\ORM\EntityRepository {
	public function getAllSubscribers() {
		$db = $this->getEntityManager()->getConnection();
		$query="SELECT device_id FROM subscriptor;";
		$stmt = $db->prepare($query);
		$stmt->execute();

		return $stmt->fetchAll();
	}

}
