niveles :
  type: rest
  resource:     "AppBundle:NivelesRest"
  name_prefix:  api_

tips :
  type: rest
  resource:     "AppBundle:TipsRest"
  name_prefix:  api_

subscriptores :
    type: rest
    resource: app_bundle.controller.subscriptor
    name_prefix:  api_