services:
#    app.example:
#        class: AppBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    manager.rios:
        class: AppBundle\Services\RiosManager
        arguments:
            container: '@service_container'
        tags:
            - { name: manager.rios, alias: manager.rios }